#!/bin/bash
COLOR="#A6E22E"
PAUSE_FILE="$HOME/.config/pianobar/pause"

if [ -e "$PAUSE_FILE" ]; then
    COLOR="#F92672"
    rm "$PAUSE_FILE"
else
    touch "$PAUSE_FILE"
fi
DISPLAY=`cat $HOME/.config/pianobar/nowplaying`
echo $DISPLAY
echo $DISPLAY
echo $COLOR
